diff --git a/Makefile b/Makefile
index 1696aaf..fb44df9 100644
--- a/Makefile
+++ b/Makefile
@@ -7,13 +7,13 @@
 # sets of values appear below; uncomment one of them and change the
 # directories appropriately.
 
-GLKINCLUDEDIR = ../cheapglk
-GLKLIBDIR = ../cheapglk
-GLKMAKEFILE = Make.cheapglk
+#GLKINCLUDEDIR = ../cheapglk
+#GLKLIBDIR = ../cheapglk
+#GLKMAKEFILE = Make.cheapglk
 
-#GLKINCLUDEDIR = ../glkterm
-#GLKLIBDIR = ../glkterm
-#GLKMAKEFILE = Make.glkterm
+GLKINCLUDEDIR = ../glkterm
+GLKLIBDIR = ../glkterm
+GLKMAKEFILE = Make.glkterm
 
 #GLKINCLUDEDIR = ../xglk
 #GLKLIBDIR = ../xglk
